version: "3.8"

services:

  db-client-people:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bg9FrdmCk*dLGIre
      MYSQL_DATABASE: bc_client_people
      MYSQL_USER: bc_client_people_usr
      MYSQL_PASSWORD: Bg9FrdmCk*dLGIre
    volumes:
      - mysql_data_client_people:/var/lib/mysql
      - ./sql/bc_client_people.sql:/docker-entrypoint-initdb.d/bc_client_people.sql

    ports:
      - '3307:3306'

  db-movement-account:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bg9FrdmCk*dLGIre
      MYSQL_DATABASE: bc_movement_account
      MYSQL_USER: bc_movement_account_usr
      MYSQL_PASSWORD: Bg9FrdmCk*dLGIre
    volumes:
      - mysql_data_movement_account:/var/lib/mysql
      - ./sql/bc_movement_account.sql:/docker-entrypoint-initdb.d/bc_movement_account.sql
    ports:
      - '3308:3306'

  ### Zookeeper
  zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:7.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  mysql_data_client_people:
  mysql_data_movement_account: